### PR TITLE
fix: move the bdd tests for vault with tls into versions repository

### PR DESCRIPTION
**Pull request by ccojocar**
part of https://github.com/jenkins-x/jx/issues/5868

### CODE REVIEW

**Comment by abayer** [comment]
Don't we still want to run `boot-vault` with TLS on `jenkins-x-boot-config` PRs as well as `jenkins-x-versions` PRs?

**Comment by ccojocar** [comment]
I am not sure. I think that it is enough in the versions even though some issue introduced by the boot config might be caught later.

**Comment by abayer** [comment]
Fair enough.

**Pull request merged**
